import { IniReader } from "./ini_reader.js";

const ROOM_TEMPLATES = new IniReader("src/data/rooms.ini"),
  ROOM_SCALE = 8.0 / 2048.0,
  ZONEAMOUNT = 3,
  MAP_WIDTH = 18, // Normally loaded from `options.ini`|>options|>map size
  MAP_HEIGHT = 18, // Normally loaded from `options.ini`|>options|>map size
  ROOM1 = 1,
  ROOM2 = 2,
  ROOM2C = 3,
  ROOM3 = 4,
  ROOM4 = 5,
  SHAPES = {
    1: "1",
    2: "2",
    3: "2C",
    4: "3",
    5: "4",
  },
  ZONECOLOR = {
    0: "#ffffff",
    1: "#00ffff",
    2: "#f4cccc",
    3: "#fff2cc",
  },
  GRIDSIZE = 10,
  DEVIATION_CHANCE = 40,
  BRANCH_CHANCE = 65,
  BRANCH_MAX_LIFE = 4,
  BRANCH_DIE_CHANCE = 18,
  MAX_DEVIATION_DISTANCE = 3,
  RETURN_CHANCE = 27,
  CENTER = 5;

export {
  ROOM_TEMPLATES,
  ROOM_SCALE,
  ZONEAMOUNT,
  MAP_WIDTH,
  MAP_HEIGHT,
  ROOM1,
  ROOM2,
  ROOM2C,
  ROOM3,
  ROOM4,
  SHAPES,
  ZONECOLOR,
  GRIDSIZE,
  DEVIATION_CHANCE,
  BRANCH_CHANCE,
  BRANCH_MAX_LIFE,
  BRANCH_DIE_CHANCE,
  MAX_DEVIATION_DISTANCE,
  RETURN_CHANCE,
  CENTER,
};
